name: 'Composite Action'
description: 'This workflow is able to build and push a specified Image from Tutor to Docker Hub.'

inputs:
  python-version:
    description: 'Version of Python. It is useful since venv will be created from it.'
    required: false
    default: '3.8'
  tutor-version:
    description: 'Tutor version to be installed. It takes 15.3.0 by default.'
    required: true
    default: '15.3.0'
  repository-name:
    description: 'Name of the repository in Docker Hub.'
    required: true
  path-image-to-be-built:
    description: 'Image to be built.'
    required: true
  image-name:
    description: 'This input refers the name of the image that will be pushed to Docker Hub.'
    required: true
  image-tag:
    description: 'Tag of the image that will be pushed to Docker Hub. It assigns latest by default.'
    required: false
    default: 'latest'
  docker-username:
    description: 'Docker Hub username.'
    required: true
  docker-token:
    description: 'Docker Hub token.'
    required: true
  no-docker-cache:
    description: 'Determines whether to use caching during image building.'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Cache Tutor requirements
      id: cache-pip
      uses: actions/cache@v3
      env:
        cache-name: cache-pip-requirements
      with:
        path: ./venv
        key: ${{ runner.os }}-${{ env.cache-name }}-requirements
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Create and activate the env
      run: |
        python -m venv venv
        source venv/bin/activate
      shell: bash

    - name: Install Tutor
      run: |
        source venv/bin/activate
        python -m pip install tutor==${{ inputs.tutor-version }}
      shell: bash

    - name: Render Tutor Templates
      run: |
        source venv/bin/activate
        tutor config save
      shell: bash

    - name: Setup buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-token }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: /home/runner/.local/share/tutor/${{ inputs.path-image-to-be-built }}
        push: true
        tags: "${{ inputs.repository-name }}/${{ inputs.image-name }}:${{ inputs.image-tag }}"
        no-cache: ${{ inputs.no-docker-cache }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
