name: 'Composite Action'
description: 'This workflow is able to build and push a specified Image from Tutor to Docker Hub.'

inputs:
  gh-access-token:
    description: 'Personal Access Token (PAT). If you have not configured it yet, \
                  enter here https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) to see how create a PAT. \
                  When it is already configured, you can add it as a secrets for the repository. \
                  To see how create a secret enter https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository.'
    required: true


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Create and activate the env
      run: |
        python -m venv venv
        source venv/bin/activate
      shell: bash

    - name: Install Tutor
      run: |
        source venv/bin/activate
        python -m pip install tutor==15.3.3
      shell: bash

    - name: tutor ecommerce
      run: |
        source venv/bin/activate
        git clone https://${{ inputs.gh-access-token }}@github.com/Pearson-Advance/tutor-ecommerce.git
        pip install -e ./tutor-ecommerce
        tutor plugins enable discovery ecommerce mfe
        tutor local launch
        tutor config save
        tutor images build ecommerce
      shell: bash


