name: 'Composite Action'
description: 'This workflow is able to build and push a specified Image from Tutor to Docker Hub.'

inputs:
  docker-username:
    description: 'Docker Hub username.'
    required: true
  docker-token:
    description: 'Docker Hub token.'
    required: true
  gh-access-token:
    description: 'Personal Access Token (PAT). If you have not configured it yet, \
                  enter here https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) to see how create a PAT. \
                  When it is already configured, you can add it as a secrets for the repository. \
                  To see how create a secret enter https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository.'
    required: true


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Create and activate the env
      run: |
        python -m venv venv
        source venv/bin/activate
      shell: bash

    - name: Install Tutor
      run: |
        source venv/bin/activate
        python -m pip install tutor==15.3.3
      shell: bash

    - name: tutor ecommerce
      run: |
        source venv/bin/activate
        git clone -b PADV-377.test https://github.com/Pearson-Advance/tutor-ecommerce.git
        pip install -e ./tutor-ecommerce
        tutor plugins enable discovery ecommerce mfe
        tutor config save
        tutor images build ecommerce --build-arg --tag=pearsonopenedxops/tutor-ecommerce:latest
      shell: bash

    - name: Setup buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-token }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: /home/runner/.local/share/tutor/env/plugins/ecommerce/build/ecommerce/
        push: true
        tags: pearsonopenedxops/tutor-ecommerce:latest
        no-cache: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
