name: 'Composite Action'
description: 'This workflow is able to build and push a specified Image from Tutor to Docker Hub.'

inputs:
  python-version:
    description: 'Version of Python. It is useful since venv will be created from it.'
    required: false
    default: '3.8'
  tutor-version:
    description: 'Tutor version to be installed. It takes 15.3.0 by default.'
    required: true
    default: '15.3.0'
  repository-name:
    description: 'Name of the repository in Docker Hub.'
    required: true
  image-to-be-built:
    description: 'Image to be built.'
    required: true
  image-name:
    description: 'This input refers the name of the image that will be pushed to Docker Hub.'
    required: true
  image-tag:
    description: 'Tag of the image that will be pushed to Docker Hub. It assigns latest by default.'
    required: false
    default: 'latest'
  docker-username:
    description: 'Docker Hub username.'
    required: true
  docker-token:
    description: 'Docker Hub token.'
    required: true

runs:
  using: "composite"
  steps:

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Create and activate the env
      run: |
        python -m venv venv
        source venv/bin/activate
      shell: bash

    - name: Install Tutor
      run: pip install tutor==${{ inputs.tutor-version }}
      shell: bash

    - name: Render Tutor Templates
      run: tutor config save
      shell: bash

    - name: Build image
      run: |
        tutor images build ${{ inputs.image-to-be-built }} \
            --docker-arg --tag="${{ inputs.repository-name }}/${{ inputs.image-name }}:${{ inputs.image-tag }}"
      shell: bash

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-token }}

    - name: Push image to DockerHub
      run: docker push ${{ inputs.repository-name }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
      shell: bash
