name: Test

on:
  workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: Pearson-Advance/tutor-build-image-action
          ref: VUE/PADV-329

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.python_version }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: python -m pip install --upgrade pip

      - run: export INPUT_GH_ACCESS_TOKEN=${{ secrets.GH_PAT }}

      - run: npm install

      - run: npm test
